# API

### Login
POST http://localhost:9091/admin/login
Content-Type: application/json

{
    "email": "suphansa-ng@rmutp.ac.th", 
    "password": "s@2004", 
    "rememberMe": false
}

### Forgot
GET http://localhost:9091/admin/forgot-password
Content-Type: application/json

{
    "email": "suphansa-ng@rmutp.ac.th"
}

### Profile
GET http://localhost:9091/admin/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzg3NjU0OTcwLCJleHAiOjE3OTAyNDY5NzB9.5aPijQglbQgZklmDpwnUIFTTFXbRNh8fOghda43fswc

### Register / Signup
GET http://localhost:9091/admin/register-admin
Content-Type: application/json

{
    "email": "suphansa-ng@rmutp.ac.th",
    "password": "s@2004",
    "firstname": "Suphansa",
    "lastname": "Ngamaksron"
}